check_in_task:
  description: >
    Here is the user's current calendar:

    {calendar}

    If the user's calendar is not empty and there exists a *past* event row with "[Empty]" left in the feedback column
    of that row, ask the user how he/she feels about that event. Otherwise, just output a single 'None'.
    
    Note that the current time is {current_time}.
  expected_output: >
    A nice chat asking the user how the event was, or 'None'.
  agent: checkInAgent

calendar_event_task:
  description: >
    You should:
    (1) For each row in the current calendar, if the feedback of that event is "[Empty]" and the context contains
    information about the user's feedback to that event, replace the "[Empty]" in that row with a concise description
    of the feedback.
    (2) For any upcoming event that appears in the context, create a new row in the calendar with ABSOLUTE DATES:
       - Convert relative time references (like "next Sunday") to actual calendar dates (like "2025-05-11")
       - If the user mentions "next Sunday", calculate the exact date based on today's date ({current_time})
       - Use YYYY-MM-DD format for all dates
    (3) For the Schedule, mention what is about to happen. Summarize what the user plans to do in one sentence

    CONTEXT: {chat_history}
    Today's date is: {current_time}
    The current calendar is: {calendar}
    You should fill in the "Feedback" part of that new row with "[Empty]".
    Do not remove any rows from the current calendar unless that event has been rescheduled or cancelled.
  expected_output: >
    A raw JSON list containing objects with 'Time', 'Schedule', and 'Feedback' keys. Do not include markdown style. Never use "```"" or "json" in the output.
  agent: calendar_agent