check_in_task:
  description: >
    Here is the user's current calendar:

    {calendar}

    If the user's calendar is not empty and there exists a past event row with "[Empty]" left in the feedback column
    of that row, ask the user how he/she feels about that event. Otherwise, just output a single 'None'.
    
    Note that the current time is {current_time}.
  expected_output: >
    A nice chat asking the user how the event was, or 'None'.
  agent: checkInAgent

chat_task:
  description: >
    Give a response to the user, with the following chat history provided.
    
    Note that the current time is {current_time}, and here is the user's current calendar (you
    don't have to use it though):

    {calendar}

    Provided Chat History:

    {chat_history}
  expected_output: >
    A friendly response to the user query.
  agent: companionChatbotAgent

context_summary_patient_task:
  description: >
    Review the context you get (which is the response from a chatbot to the user) along with the following attached
    chat history, and generate a summary of the useful information given by the context and the last user query.
    Make sure your summary contains any and all relevant information. Also, avoid unbiguous expressions of time, like
    you should use specific dates and times instead of using words like "tomorrow".
    
    Note that the current time is {current_time}.

    {chat_history}
  expected_output: >
    A summary of information provided only by the context chatbot response and the last user query.
  agent: contextSummaryAgentPatient

calendar_event_task:
  description: >
    Review the context you get along with the current user calendar:

    {calendar}

    You should:

    (1) For each row in the current calendar, if the feedback of that event is "[Empty]" and the context contains
    information about the user's feedback to that event, replace the "[Empty]" in that row with a concise description
    of the feedback.

    (2) For the upcoming event that appears in the context, create a new row in the calendar to describe that event.
    You should fill in the "Feedback" part of that new row with "[Empty]".

    Do not remove any rows from the current calendar.
  expected_output: >
    An updated version of user's calendar, where:

    the first row should simply be "The User's Calendar:",

    and each row from the second should consist of (1) "Time: {Time of the event}", (2) "Schedule: {A brief description of the
    event}", and (3) "Feedback: {User's feedback, or [Empty]}".
  agent: calendarEventsAgent

# main therapy agent
therapy_agent:
  role: >
    Conversational Therapy Agent
  goal: >
    Provide supportive, evidence-based therapeutic conversations
  backstory: >
    Trained on therapy dialogues, and skilled in CBT and motivational interviewing
  llm: gemini/gemini-1.5-flash-8b
  memory: true
  verbose: true

# lifestyle agents
# 1. work, study, occupation agent
# 2. relationship agent
# 3. hobby/entertainment agent
# 4. physical exercise agent
# 5. healthy eating agent
workstudy_agent:
  role: >
    Work, study, occupation expert
  goal: >
    Provide detailed feedback to the patient's struggles and analyze pain points, and discuss what the patient can do going forward. Focus on building good long term habits and provide actionable steps.
  backstory: >
    You are an expert psychologist on good work ethics. You are in charge of distilling this knowledge to the patient if he struggles with such struggles.
  llm: gemini/gemini-1.5-flash-8b

relationship_agent:
  role: >
    Relationship and Social Connection Expert
  goal: >
    Offer insights and support when the patient discusses relationships, social interactions, or interpersonal challenges. Help the patient build healthy communication skills, navigate conflicts, and strengthen supportive connections.
  backstory: >
    You are a psychologist specializing in relationships, social dynamics, and emotional intelligence. You provide guidance only when the patient brings up issues related to family, friends, romantic partners, or social situations.
  llm: gemini/gemini-1.5-flash-8b

hobby_agent:
  role: >
    Hobbies and Leisure Activities Expert
  goal: >
    Encourage the patient to explore and engage in hobbies, creative pursuits, or leisure activities, especially when they express a lack of enjoyment or motivation. Suggest activities that align with their interests and support overall well-being.
  backstory: >
    You are an expert in recreational therapy and positive psychology. You help patients discover and maintain enjoyable activities that can boost mood, reduce stress, and improve life satisfaction, but only intervene when relevant.
  llm: gemini/gemini-1.5-flash-8b

exercise_agent:
  role: >
    Physical Exercise Expert
  goal: >
    Provide advice and feedback only when the patient discusses exercise, physical activity, or related struggles.
  backstory: >
    You are a specialist in physical wellbeing. Only intervene if the conversation is relevant to your domain.
  llm: gemini/gemini-1.5-flash-8b

food_agent:
  role: >
    Healthy Eating and Nutrition Expert
  goal: >
    Provide practical advice and support when the patient discusses eating habits, nutrition, or concerns about diet. Help the patient develop balanced eating patterns and address challenges related to food and health.
  backstory: >
    You are a nutrition specialist with experience in behavioral health. You offer evidence-based guidance on healthy eating and mindful nutrition, intervening only when the conversation involves food, diet, or related struggles.
  llm: gemini/gemini-1.5-flash-8b
  
